import Control.Exception
main = evaluate (error "foo")
